networks:
  wireguard:
    driver: bridge
    enable_ipv6: true 
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
        
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    networks:
      - wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - INSECURE=true
    volumes:
      - ./wireguard:/etc/wireguard # Directorio para archivos persistentes.
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
      
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: raspberrypi # Nombre de tu dispositivo.
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Madrid # Zona horaria.
      - FTLCONF_webserver_api_password=tupassword # Password de acceso a Pi-hole.
     # - FTLCONF_webserver_port=8080,8443s # Opcional: cambiar puertos 80:80 (HTTP) y 443:443 (HTTPS) para acceso web.
      - FTLCONF_dns_listeningMode=LOCAL
     # - FTLCONF_dns_specialDomains_iCloudPrivateRelay=true # Opcional: relay privado de Apple.
      - PIHOLE_UID=1000 # UID de tu máquina. Comprobar con comando: id -u
      - PIHOLE_GID=1000 # UID de tu máquina. Comprobar con comando: id -g
    volumes:
      - ./pihole:/etc/pihole # Directorio para archivos persistentes.
    cap_add:
     # - NET_ADMIN # Opcional: usar Pi-hole como servidor DHCP.
     # - SYS_TIME # Opcional: usar Pi-hole como cliente NTP.
      - SYS_NICE
 
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # UID de tu máquina. Comprobar con comando: id -u
      - PGID=1000 # UID de tu máquina. Comprobar con comando: id -g
      - TZ=Europe/Madrid # Zona horaria.
      - SUBDOMAINS=tusubdominio # Nombre del subdominio creado en duckdns.org
      - TOKEN=tutoken # Token de Duck DNS.
      - UPDATE_IP=both
      - LOG_FILE=false
    volumes:
      - ./duckdns:/config # Directorio para archivos persistentes.
