networks:
  wireguard_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        
  pihole_macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0 # Interfaz de red de tu máquina. Comprobar con comando: ip route | grep default
    ipam:
      config:
        - subnet: 192.168.1.0/24 # Rango de IPs de tu red local.
          gateway: 192.168.1.1 # IP de tu router.
        
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    networks:
      - wireguard_net
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
     # Comprobar puertos libres con comando: sudo ss -tulpn | grep :puerto 
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - INSECURE=true
    volumes:
      - ./wireguard:/etc/wireguard # Directorio para archivos persistentes.
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: ugreennas # Nombre de tu dispositivo.
    restart: unless-stopped
    networks:
      pihole_macvlan:
        ipv4_address: 192.168.1.5 # IP libre en tu LAN para Pi-hole.
    environment:
      - TZ=Europe/Madrid #Zona horaria. Comprobar aquí: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - FTLCONF_webserver_api_password=tupassword # Password de acceso a Pi-hole.
      - FTLCONF_dns_listeningMode=ALL
     # - FTLCONF_dns_specialDomains_iCloudPrivateRelay=true # Opcional: relay privado de Apple.
      - PIHOLE_UID=1000 # UID de tu máquina. Comprobar con comando: id -u
      - PIHOLE_GID=10 # GID de tu máquina. Comprobar con comando: id -g
    volumes:
      - ./pihole:/etc/pihole # Directorio para archivos persistentes.
    cap_add:
     # - NET_ADMIN # Opcional: usar Pi-hole como servidor DHCP.
     # - SYS_TIME # Opcional: usar Pi-hole como cliente NTP.
      - SYS_NICE
      
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # UID de tu máquina. Comprobar con comando: id -u
      - PGID=1000 # UID de tu máquina. Comprobar con comando: id -g
      - TZ=Europe/Madrid # Zona horaria. Comprobar aquí: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - SUBDOMAINS=tusubdominio # Nombre del subdominio creado en duckdns.org
      - TOKEN=tutoken # Token de Duck DNS.
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ./duckdns:/config # Directorio para archivos persistentes.
